#! /usr/bin/env zsh
#curl --data "message=$1. You asked to be notified." "https://sms.varal7.fr/api.php?token=db6e2fd80cc11b01a6689a04e13cc412&number=0635113309"
sendsms 0600000000 "$1. Requested notifcation"
